<?php

$config = array(
    'host' => '10.10.10.205',
    'port' => '3306',
    'username' => 'root',
    'password' => 'ccit132456',
    'dbname' => 'block',
    'prefix' => 'block_',
    'dsn' => 'mysql:host=10.10.10.205;port=3306;dbname=block',
    'type'=>array(
        1=>'btc',
        2=>'eth',
        3=>'bcd',
        4=>'elf',
        5=>'ink',
        6=>'trx',
        7=>'aidoc',
        8=>'pst',
        9=>'ddd',
        10=>'eko',
        11=>'pra',
        12=>'uc',
        13=>'aif',
        14=>'bch',
        15=>'bcx',
        16=>'etc',
        17=>'ltc',
        18=>'sbtc',
        19=>'qtum',
        20=>'neo',
        21=>'nem',
        22=>'hsr',
        23=>'xrp',
        24=>'dash',
        25=>'xmr',
        26=>'eos',
        27=>'omg',
        28=>'iota',
        29=>'zec',
        30=>'waves',
        31=>'btg',
        32=>'bts',
        33=>'xlm',
        34=>'lsk'
    )
    );
